# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Virtual_Instruments.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(479, 300)
        self.C = QtWidgets.QPushButton(Dialog)
        self.C.setGeometry(QtCore.QRect(70, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C.sizePolicy().hasHeightForWidth())
        self.C.setSizePolicy(sizePolicy)
        self.C.setObjectName("C")
        self.CD = QtWidgets.QPushButton(Dialog)
        self.CD.setGeometry(QtCore.QRect(100, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CD.sizePolicy().hasHeightForWidth())
        self.CD.setSizePolicy(sizePolicy)
        self.CD.setObjectName("CD")
        self.D = QtWidgets.QPushButton(Dialog)
        self.D.setGeometry(QtCore.QRect(130, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D.sizePolicy().hasHeightForWidth())
        self.D.setSizePolicy(sizePolicy)
        self.D.setObjectName("D")
        self.DD = QtWidgets.QPushButton(Dialog)
        self.DD.setGeometry(QtCore.QRect(160, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DD.sizePolicy().hasHeightForWidth())
        self.DD.setSizePolicy(sizePolicy)
        self.DD.setObjectName("DD")
        self.E = QtWidgets.QPushButton(Dialog)
        self.E.setGeometry(QtCore.QRect(190, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E.sizePolicy().hasHeightForWidth())
        self.E.setSizePolicy(sizePolicy)
        self.E.setObjectName("E")
        self.F = QtWidgets.QPushButton(Dialog)
        self.F.setGeometry(QtCore.QRect(220, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F.sizePolicy().hasHeightForWidth())
        self.F.setSizePolicy(sizePolicy)
        self.F.setObjectName("F")
        self.FD = QtWidgets.QPushButton(Dialog)
        self.FD.setGeometry(QtCore.QRect(250, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FD.sizePolicy().hasHeightForWidth())
        self.FD.setSizePolicy(sizePolicy)
        self.FD.setObjectName("FD")
        self.G = QtWidgets.QPushButton(Dialog)
        self.G.setGeometry(QtCore.QRect(280, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G.sizePolicy().hasHeightForWidth())
        self.G.setSizePolicy(sizePolicy)
        self.G.setObjectName("G")
        self.GD = QtWidgets.QPushButton(Dialog)
        self.GD.setGeometry(QtCore.QRect(310, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GD.sizePolicy().hasHeightForWidth())
        self.GD.setSizePolicy(sizePolicy)
        self.GD.setObjectName("GD")
        self.A = QtWidgets.QPushButton(Dialog)
        self.A.setGeometry(QtCore.QRect(340, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A.sizePolicy().hasHeightForWidth())
        self.A.setSizePolicy(sizePolicy)
        self.A.setObjectName("A")
        self.AD = QtWidgets.QPushButton(Dialog)
        self.AD.setGeometry(QtCore.QRect(370, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AD.sizePolicy().hasHeightForWidth())
        self.AD.setSizePolicy(sizePolicy)
        self.AD.setObjectName("AD")
        self.B = QtWidgets.QPushButton(Dialog)
        self.B.setGeometry(QtCore.QRect(400, 60, 31, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B.sizePolicy().hasHeightForWidth())
        self.B.setSizePolicy(sizePolicy)
        self.B.setObjectName("B")
        self.instr = QtWidgets.QLabel(Dialog)
        self.instr.setGeometry(QtCore.QRect(210, 200, 191, 20))
        self.instr.setObjectName("instr")
        self.naz = QtWidgets.QPushButton(Dialog)
        self.naz.setGeometry(QtCore.QRect(110, 230, 75, 23))
        self.naz.setObjectName("naz")
        self.vpe = QtWidgets.QPushButton(Dialog)
        self.vpe.setGeometry(QtCore.QRect(290, 230, 75, 23))
        self.vpe.setObjectName("vpe")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.C.setText(_translate("Dialog", "C"))
        self.CD.setText(_translate("Dialog", "C#"))
        self.D.setText(_translate("Dialog", "D"))
        self.DD.setText(_translate("Dialog", "D#"))
        self.E.setText(_translate("Dialog", "E"))
        self.F.setText(_translate("Dialog", "F"))
        self.FD.setText(_translate("Dialog", "F#"))
        self.G.setText(_translate("Dialog", "G"))
        self.GD.setText(_translate("Dialog", "G#"))
        self.A.setText(_translate("Dialog", "A"))
        self.AD.setText(_translate("Dialog", "A#"))
        self.B.setText(_translate("Dialog", "B"))
        self.instr.setText(_translate("Dialog", "СИНТЕЗАТОР"))
        self.naz.setText(_translate("Dialog", "<--"))
        self.vpe.setText(_translate("Dialog", "-->"))

